//! Golden-vector loader. Cases live in rust/tests/data/<name>/ as raw
//! little-endian binaries + a manifest.json, generated by
//! rust/python/gen_golden.py (which records the generating commit in
//! rust/tests/data/meta.json). Regenerate with:
//!     .venv/bin/python rust/python/gen_golden.py

#![allow(dead_code)] // each test binary uses its own subset of these helpers

use std::fs;
use std::path::PathBuf;

use num_complex::Complex64;
use serde_json::Value;

pub struct Case {
    dir: PathBuf,
    manifest: Value,
}

impl Case {
    pub fn load(name: &str) -> Case {
        let dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("tests/data")
            .join(name);
        let text = fs::read_to_string(dir.join("manifest.json")).unwrap_or_else(|e| {
            panic!(
                "missing golden case '{}' ({e}); run .venv/bin/python rust/python/gen_golden.py",
                name
            )
        });
        let manifest = serde_json::from_str(&text).expect("manifest.json parse");
        Case { dir, manifest }
    }

    fn array_entry(&self, key: &str) -> (&Value, Vec<u8>) {
        let entry = &self.manifest["arrays"][key];
        assert!(!entry.is_null(), "no array '{key}' in manifest");
        let file = entry["file"].as_str().unwrap();
        let bytes = fs::read(self.dir.join(file)).expect("array file read");
        (entry, bytes)
    }

    fn checked(&self, key: &str, want_dtype: &str) -> Vec<u8> {
        let (entry, bytes) = self.array_entry(key);
        let dtype = entry["dtype"].as_str().unwrap();
        assert_eq!(dtype, want_dtype, "array '{key}': manifest dtype mismatch");
        bytes
    }

    pub fn shape(&self, key: &str) -> Vec<usize> {
        self.manifest["arrays"][key]["shape"]
            .as_array()
            .unwrap_or_else(|| panic!("no array '{key}'"))
            .iter()
            .map(|v| v.as_u64().unwrap() as usize)
            .collect()
    }

    pub fn f64s(&self, key: &str) -> Vec<f64> {
        self.checked(key, "f64")
            .chunks_exact(8)
            .map(|c| f64::from_le_bytes(c.try_into().unwrap()))
            .collect()
    }

    pub fn f32s(&self, key: &str) -> Vec<f32> {
        self.checked(key, "f32")
            .chunks_exact(4)
            .map(|c| f32::from_le_bytes(c.try_into().unwrap()))
            .collect()
    }

    /// complex128 stored as interleaved little-endian f64 (re, im). Row-major
    /// for 2-D arrays; pair with `shape()`.
    pub fn c128s(&self, key: &str) -> Vec<Complex64> {
        let vals: Vec<f64> = self
            .checked(key, "c128")
            .chunks_exact(8)
            .map(|c| f64::from_le_bytes(c.try_into().unwrap()))
            .collect();
        vals.chunks_exact(2)
            .map(|p| Complex64::new(p[0], p[1]))
            .collect()
    }

    /// complex64 stored as interleaved little-endian f32 (re, im), returned as
    /// (re, im) f32 pairs so bit-level comparisons stay exact.
    pub fn c64s(&self, key: &str) -> Vec<(f32, f32)> {
        let vals: Vec<f32> = self
            .checked(key, "c64")
            .chunks_exact(4)
            .map(|c| f32::from_le_bytes(c.try_into().unwrap()))
            .collect();
        vals.chunks_exact(2).map(|p| (p[0], p[1])).collect()
    }

    pub fn scalar_f64(&self, key: &str) -> f64 {
        self.manifest["scalars"][key]
            .as_f64()
            .unwrap_or_else(|| panic!("no f64 scalar '{key}'"))
    }

    pub fn scalar_usize(&self, key: &str) -> usize {
        self.manifest["scalars"][key]
            .as_u64()
            .unwrap_or_else(|| panic!("no int scalar '{key}'")) as usize
    }

    pub fn scalar_str(&self, key: &str) -> String {
        self.manifest["scalars"][key]
            .as_str()
            .unwrap_or_else(|| panic!("no str scalar '{key}'"))
            .to_string()
    }
}

/// Distance in units-in-the-last-place between two f32s, on the monotonic
/// integer mapping (so +0 and -0 are 0 apart, and values straddling 0 count
/// the denormal steps between them).
pub fn ulp_dist_f32(a: f32, b: f32) -> u64 {
    fn monotonic(x: f32) -> i64 {
        let b = x.to_bits();
        if b & 0x8000_0000 != 0 {
            -((b & 0x7fff_ffff) as i64)
        } else {
            b as i64
        }
    }
    assert!(!a.is_nan() && !b.is_nan(), "NaN in c64 comparison");
    (monotonic(a) - monotonic(b)).unsigned_abs()
}

/// Relative error |a-b| / max(|b|, floor); `floor` guards zero-valued expected
/// elements (use ~1e-3 x the max magnitude of the expected array).
pub fn rel_err_c(a: Complex64, b: Complex64, floor: f64) -> f64 {
    (a - b).norm() / b.norm().max(floor)
}
